version: "3.8"

services:
  config-server:
    build:
      context: ./config-service
    container_name: config-server
    ports:
      - "8888:8888"
    volumes:
      - ./config-repo:/config

  eureka:
    build:
      context: ./discovery-service
    container_name: eureka
    ports:
      - "8761:8761"

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    ports:
      - "8081:8081"
    depends_on:
      - config-server
      - eureka
      - postgres

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    ports:
      - "8082:8082"
    depends_on:
      - config-server
      - eureka
      - postgres

  transaction-service:
    build: ./transaction-service
    depends_on:
      - config-server
      - postgres
    ports:
      - "8083:8080"

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: fintrack
      POSTGRES_PASSWORD: fintrack123
      POSTGRES_DB: fintrack_userdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql:ro
volumes:
  pgdata: