spring:
  application:
    name: transaction-service

---

spring:
  config:
    activate:
      on-profile: local
    import: optional:configserver:http://localhost:8888

---

spring:
  config:
    activate:
      on-profile: docker
    import: optional:configserver:http://config-server:8888
